/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "types.h"

bool_t
xdr_tagtype (XDR *xdrs, tagtype *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_file (XDR *xdrs, file *objp)
{
	register int32_t *buf;

	 if (!xdr_bytes (xdrs, (char **)&objp->contents.contents_val, (u_int *) &objp->contents.contents_len, ~0))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->last_mod_time))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_message (XDR *xdrs, message *objp)
{
	register int32_t *buf;

	 if (!xdr_tagtype (xdrs, &objp->tag))
		 return FALSE;
	switch (objp->tag) {
	case GET:
		 if (!xdr_string (xdrs, &objp->message_u.filename, 256))
			 return FALSE;
		break;
	case OK:
		 if (!xdr_file (xdrs, &objp->message_u.fdata))
			 return FALSE;
		break;
	case QUIT:
		break;
	case ERR:
		break;
	default:
		return FALSE;
	}
	return TRUE;
}
